name: Python application

on: 
  push:
    branches: [ main, workflow_dispatch ]
permissions:
  id-token: write
  contents: read

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-



    - name: Run Python Script
      run: python ./mypython.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          mypython.py
          
    - name:  Some step that requires the token
      run: |
        echo Using the GitHub token!
      env:
        MY_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 
  Deploy: 
     needs: Build
     runs-on: ubuntu-latest
     steps:      
       - name: Ey bidda idi na adda
         run: echo "Deploying "Ey bidda idi na adda""
