name: Python application

on: 
  push:
    branches: [ main, workflow_dispatch ]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python Script
      run: python ./mypython.py
 
  Deploy: 
     needs: Build
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2
       - name: Install nodejs
         uses: actions/setup-node@v2         
         with:
           node-version: 18
       - name: Install dependencies
         run: npm ci
       - name: Ey bidda idi na adda
         run: echo "Deploying "Ey bidda idi na adda""
