name: Simple Python Workflow with Inputs and Outputs

on:
  workflow_dispatch:
    inputs:
      inputValue:
        description: 'Input Value'
        required: true
        default: 'Hello World'

jobs:
  process-input:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Process Input
      id: processing
      run: |
        echo "Received Input: ${{ github.event.inputs.inputValue }}"
        outputValue="${{ github.event.inputs.inputValue }} from GitHub Actions!"
        echo "::set-output name=outputValue::$outputValue"

    - name: Display Processed Output
      run: echo "Processed Output::${{ steps.processing.outputs.outputValue }}"

